version: '3'

services:
        # mongo:
        #   image: mongo
        #   restart: always
        #   environment:
        #     MONGO_INITDB_ROOT_USERNAME: root
        #     MONGO_INITDB_ROOT_PASSWORD: example
        #   ports:  
        #     - 27017:27017
        #   volumes:
        #   - ./mongo_data:/data/db

        # mongo-express:
        #   image: mongo-express
        #   restart: always
        #   ports:
        #     - 8081:8081
        #   environment:
        #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
        #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  # blacklab-server:
  #   build:
  #     context: .
  #   ports:
  #     - "8887:8080"
  #   volumes:
  #     - ./indexes:/data/blacklab/indexes

  django:
    build: .
    image: pttweb:1.0
    restart: always
    ports:
      - 9898:8888
    env_file:
      - pttweb.env
    command: >
      sh -c "
      python manage.py migrate --no-input
      && python manage.py collectstatic --no-input
      && uwsgi --master --http 0.0.0.0:8888 --module web.wsgi --static-map /static_pttweb=static_pttweb --process 4 --manage-script-name --mount=/pttcorp=web/wsgi.py"

    volumes:
    # - ./vrt_data:/app/cwb/vrt
    # - ./cwb_registry:/app/cwb/registry
    # - ./cwb_data:/app/cwb/data
    - ./scripts:/app/scripts
    - ./core:/app/core
    - ./templates:/app/templates
    
      # depends_on:
      # - mongo
      # - mongo-express
